{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "initial_id",
   "metadata": {
    "collapsed": true,
    "ExecuteTime": {
     "end_time": "2023-12-05T16:36:47.269965082Z",
     "start_time": "2023-12-05T16:36:44.046989974Z"
    }
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_trace_dispatch_regular.py\", line 429, in __call__\n",
      "    abs_path_real_path_and_base = NORM_PATHS_AND_BASE_CONTAINER[frame.f_code.co_filename]\n",
      "KeyError: '/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py\", line 586, in get_abs_path_real_path_and_base_from_frame\n",
      "    return NORM_PATHS_AND_BASE_CONTAINER[frame.f_code.co_filename]\n",
      "NameError: name 'NORM_PATHS_AND_BASE_CONTAINER' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_trace_dispatch_regular.py\", line 431, in __call__\n",
      "    abs_path_real_path_and_base = get_abs_path_real_path_and_base_from_frame(frame)\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py\", line 593, in get_abs_path_real_path_and_base_from_frame\n",
      "    if get_abs_path_real_path_and_base_from_file is None:  # Interpreter shutdown\n",
      "NameError: name 'get_abs_path_real_path_and_base_from_file' is not defined\n",
      "Traceback (most recent call last):\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_trace_dispatch_regular.py\", line 429, in __call__\n",
      "    abs_path_real_path_and_base = NORM_PATHS_AND_BASE_CONTAINER[frame.f_code.co_filename]\n",
      "KeyError: '/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py\", line 586, in get_abs_path_real_path_and_base_from_frame\n",
      "    return NORM_PATHS_AND_BASE_CONTAINER[frame.f_code.co_filename]\n",
      "NameError: name 'NORM_PATHS_AND_BASE_CONTAINER' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_trace_dispatch_regular.py\", line 431, in __call__\n",
      "    abs_path_real_path_and_base = get_abs_path_real_path_and_base_from_frame(frame)\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py\", line 593, in get_abs_path_real_path_and_base_from_frame\n",
      "    if get_abs_path_real_path_and_base_from_file is None:  # Interpreter shutdown\n",
      "NameError: name 'get_abs_path_real_path_and_base_from_file' is not defined\n",
      "Traceback (most recent call last):\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_trace_dispatch_regular.py\", line 429, in __call__\n",
      "    abs_path_real_path_and_base = NORM_PATHS_AND_BASE_CONTAINER[frame.f_code.co_filename]\n",
      "KeyError: '/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py\", line 586, in get_abs_path_real_path_and_base_from_frame\n",
      "    return NORM_PATHS_AND_BASE_CONTAINER[frame.f_code.co_filename]\n",
      "KeyError: '/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_trace_dispatch_regular.py\", line 431, in __call__\n",
      "    abs_path_real_path_and_base = get_abs_path_real_path_and_base_from_frame(frame)\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py\", line 593, in get_abs_path_real_path_and_base_from_frame\n",
      "    if get_abs_path_real_path_and_base_from_file is None:  # Interpreter shutdown\n",
      "NameError: name 'get_abs_path_real_path_and_base_from_file' is not defined\n",
      "Traceback (most recent call last):\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_trace_dispatch_regular.py\", line 429, in __call__\n",
      "    abs_path_real_path_and_base = NORM_PATHS_AND_BASE_CONTAINER[frame.f_code.co_filename]\n",
      "KeyError: '/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py\", line 586, in get_abs_path_real_path_and_base_from_frame\n",
      "    return NORM_PATHS_AND_BASE_CONTAINER[frame.f_code.co_filename]\n",
      "KeyError: '/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_trace_dispatch_regular.py\", line 431, in __call__\n",
      "    abs_path_real_path_and_base = get_abs_path_real_path_and_base_from_frame(frame)\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py\", line 593, in get_abs_path_real_path_and_base_from_frame\n",
      "    if get_abs_path_real_path_and_base_from_file is None:  # Interpreter shutdown\n",
      "NameError: name 'get_abs_path_real_path_and_base_from_file' is not defined\n",
      "Traceback (most recent call last):\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py\", line 230, in _NormPaths\n",
      "    return NORM_PATHS_CONTAINER[filename]\n",
      "KeyError: '/usr/lib/python3.10/posixpath.py'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_trace_dispatch_regular.py\", line 429, in __call__\n",
      "    abs_path_real_path_and_base = NORM_PATHS_AND_BASE_CONTAINER[frame.f_code.co_filename]\n",
      "KeyError: '/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py\", line 586, in get_abs_path_real_path_and_base_from_frame\n",
      "    return NORM_PATHS_AND_BASE_CONTAINER[frame.f_code.co_filename]\n",
      "KeyError: '/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_trace_dispatch_regular.py\", line 431, in __call__\n",
      "    abs_path_real_path_and_base = get_abs_path_real_path_and_base_from_frame(frame)\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py\", line 593, in get_abs_path_real_path_and_base_from_frame\n",
      "    if get_abs_path_real_path_and_base_from_file is None:  # Interpreter shutdown\n",
      "NameError: name 'get_abs_path_real_path_and_base_from_file' is not defined\n",
      "Traceback (most recent call last):\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py\", line 230, in _NormPaths\n",
      "    return NORM_PATHS_CONTAINER[filename]\n",
      "KeyError: '/usr/lib/python3.10/posixpath.py'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_trace_dispatch_regular.py\", line 429, in __call__\n",
      "    abs_path_real_path_and_base = NORM_PATHS_AND_BASE_CONTAINER[frame.f_code.co_filename]\n",
      "KeyError: '/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py\", line 586, in get_abs_path_real_path_and_base_from_frame\n",
      "    return NORM_PATHS_AND_BASE_CONTAINER[frame.f_code.co_filename]\n",
      "KeyError: '/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_trace_dispatch_regular.py\", line 431, in __call__\n",
      "    abs_path_real_path_and_base = get_abs_path_real_path_and_base_from_frame(frame)\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py\", line 593, in get_abs_path_real_path_and_base_from_frame\n",
      "    if get_abs_path_real_path_and_base_from_file is None:  # Interpreter shutdown\n",
      "NameError: name 'get_abs_path_real_path_and_base_from_file' is not defined\n",
      "Traceback (most recent call last):\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py\", line 230, in _NormPaths\n",
      "    return NORM_PATHS_CONTAINER[filename]\n",
      "KeyError: '/usr/lib/python3.10/posixpath.py'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_trace_dispatch_regular.py\", line 429, in __call__\n",
      "    abs_path_real_path_and_base = NORM_PATHS_AND_BASE_CONTAINER[frame.f_code.co_filename]\n",
      "KeyError: '/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py\", line 586, in get_abs_path_real_path_and_base_from_frame\n",
      "    return NORM_PATHS_AND_BASE_CONTAINER[frame.f_code.co_filename]\n",
      "KeyError: '/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_trace_dispatch_regular.py\", line 431, in __call__\n",
      "    abs_path_real_path_and_base = get_abs_path_real_path_and_base_from_frame(frame)\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py\", line 593, in get_abs_path_real_path_and_base_from_frame\n",
      "    if get_abs_path_real_path_and_base_from_file is None:  # Interpreter shutdown\n",
      "NameError: name 'get_abs_path_real_path_and_base_from_file' is not defined\n",
      "Traceback (most recent call last):\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py\", line 230, in _NormPaths\n",
      "    return NORM_PATHS_CONTAINER[filename]\n",
      "KeyError: '/usr/lib/python3.10/posixpath.py'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_trace_dispatch_regular.py\", line 429, in __call__\n",
      "    abs_path_real_path_and_base = NORM_PATHS_AND_BASE_CONTAINER[frame.f_code.co_filename]\n",
      "KeyError: '/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py\", line 586, in get_abs_path_real_path_and_base_from_frame\n",
      "    return NORM_PATHS_AND_BASE_CONTAINER[frame.f_code.co_filename]\n",
      "KeyError: '/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_trace_dispatch_regular.py\", line 431, in __call__\n",
      "    abs_path_real_path_and_base = get_abs_path_real_path_and_base_from_frame(frame)\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py\", line 593, in get_abs_path_real_path_and_base_from_frame\n",
      "    if get_abs_path_real_path_and_base_from_file is None:  # Interpreter shutdown\n",
      "NameError: name 'get_abs_path_real_path_and_base_from_file' is not defined\n",
      "Traceback (most recent call last):\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_trace_dispatch_regular.py\", line 429, in __call__\n",
      "    abs_path_real_path_and_base = NORM_PATHS_AND_BASE_CONTAINER[frame.f_code.co_filename]\n",
      "KeyError: '/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py\", line 586, in get_abs_path_real_path_and_base_from_frame\n",
      "    return NORM_PATHS_AND_BASE_CONTAINER[frame.f_code.co_filename]\n",
      "KeyError: '/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_trace_dispatch_regular.py\", line 431, in __call__\n",
      "    abs_path_real_path_and_base = get_abs_path_real_path_and_base_from_frame(frame)\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py\", line 593, in get_abs_path_real_path_and_base_from_frame\n",
      "    if get_abs_path_real_path_and_base_from_file is None:  # Interpreter shutdown\n",
      "NameError: name 'get_abs_path_real_path_and_base_from_file' is not defined\n",
      "Traceback (most recent call last):\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_trace_dispatch_regular.py\", line 429, in __call__\n",
      "    abs_path_real_path_and_base = NORM_PATHS_AND_BASE_CONTAINER[frame.f_code.co_filename]\n",
      "KeyError: '/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py\", line 586, in get_abs_path_real_path_and_base_from_frame\n",
      "    return NORM_PATHS_AND_BASE_CONTAINER[frame.f_code.co_filename]\n",
      "KeyError: '/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_trace_dispatch_regular.py\", line 431, in __call__\n",
      "    abs_path_real_path_and_base = get_abs_path_real_path_and_base_from_frame(frame)\n",
      "  File \"/snap/pycharm-professional/359/plugins/python/helpers/pydev/pydevd_file_utils.py\", line 593, in get_abs_path_real_path_and_base_from_frame\n",
      "    if get_abs_path_real_path_and_base_from_file is None:  # Interpreter shutdown\n",
      "NameError: name 'get_abs_path_real_path_and_base_from_file' is not defined\n",
      "[autoreload of _pydevd_bundle.pydevd_frame failed: Traceback (most recent call last):\n",
      "  File \"/home/koom/repos/koo5/accounts-assessor/0/accounts-assessor/sources/services/venv/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/koom/repos/koo5/accounts-assessor/0/accounts-assessor/sources/services/venv/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/lib/python3.10/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 612, in _exec\n",
      "  File \"<frozen importlib._bootstrap>\", line 556, in _init_module_attrs\n",
      "  File \"<frozen importlib._bootstrap>\", line 397, in cached\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 513, in _get_cached\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 406, in cache_from_source\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 134, in _path_split\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 134, in <genexpr>\n",
      "NameError: name 'NO_FTRACE' is not defined\n",
      "]\n",
      "[autoreload of pydevd failed: Traceback (most recent call last):\n",
      "  File \"/home/koom/repos/koo5/accounts-assessor/0/accounts-assessor/sources/services/venv/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/koom/repos/koo5/accounts-assessor/0/accounts-assessor/sources/services/venv/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 500, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/home/koom/repos/koo5/accounts-assessor/0/accounts-assessor/sources/services/venv/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 397, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/home/koom/repos/koo5/accounts-assessor/0/accounts-assessor/sources/services/venv/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 365, in update_class\n",
      "    update_instances(old, new)\n",
      "  File \"/home/koom/repos/koo5/accounts-assessor/0/accounts-assessor/sources/services/venv/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 323, in update_instances\n",
      "    object.__setattr__(ref, \"__class__\", new)\n",
      "TypeError: __class__ assignment: 'ThreadsSuspendedSingleNotification' object layout differs from 'ThreadsSuspendedSingleNotification'\n",
      "]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The autoreload extension is already loaded. To reload it, use:\n",
      "  %reload_ext autoreload\n"
     ]
    },
    {
     "ename": "MyException",
     "evalue": "Expected one element, but got 0",
     "output_type": "error",
     "traceback": [
      "\u001B[0;31m---------------------------------------------------------------------------\u001B[0m",
      "\u001B[0;31mMyException\u001B[0m                               Traceback (most recent call last)",
      "Cell \u001B[0;32mIn[2], line 5\u001B[0m\n\u001B[1;32m      3\u001B[0m \u001B[38;5;28;01mfrom\u001B[39;00m \u001B[38;5;21;01mapp\u001B[39;00m\u001B[38;5;21;01m.\u001B[39;00m\u001B[38;5;21;01mdiv7a\u001B[39;00m \u001B[38;5;28;01mimport\u001B[39;00m \u001B[38;5;241m*\u001B[39m\n\u001B[1;32m      4\u001B[0m \u001B[38;5;66;03m#div7a2_from_json({\"loan_year\": 2020, \"full_term\": 7, \"opening_balance\": 100000.0, \"opening_balance_year\": 2020, \"repayments\": [{\"date\": \"2023-11-25\", \"amount\": 0.0}], \"lodgement_date\": \"2021-06-30\"})\u001B[39;00m\n\u001B[0;32m----> 5\u001B[0m \u001B[43mdiv7a2_from_json\u001B[49m\u001B[43m(\u001B[49m\u001B[43m{\u001B[49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[38;5;124;43mloan_year\u001B[39;49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[43m:\u001B[49m\u001B[43m \u001B[49m\u001B[38;5;241;43m2020\u001B[39;49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[38;5;124;43mfull_term\u001B[39;49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[43m:\u001B[49m\u001B[43m \u001B[49m\u001B[38;5;241;43m7\u001B[39;49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[38;5;124;43mopening_balance\u001B[39;49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[43m:\u001B[49m\u001B[43m \u001B[49m\u001B[38;5;241;43m100000.0\u001B[39;49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[38;5;124;43mopening_balance_year\u001B[39;49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[43m:\u001B[49m\u001B[43m \u001B[49m\u001B[38;5;241;43m2020\u001B[39;49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[38;5;124;43mrepayments\u001B[39;49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[43m:\u001B[49m\u001B[43m \u001B[49m\u001B[43m[\u001B[49m\u001B[43m{\u001B[49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[38;5;124;43mdate\u001B[39;49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[43m:\u001B[49m\u001B[43m \u001B[49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[38;5;124;43m2021-06-30\u001B[39;49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[38;5;124;43mamount\u001B[39;49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[43m:\u001B[49m\u001B[43m \u001B[49m\u001B[38;5;241;43m10000.0\u001B[39;49m\u001B[43m}\u001B[49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[43m{\u001B[49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[38;5;124;43mdate\u001B[39;49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[43m:\u001B[49m\u001B[43m \u001B[49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[38;5;124;43m2022-06-30\u001B[39;49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[38;5;124;43mamount\u001B[39;49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[43m:\u001B[49m\u001B[43m \u001B[49m\u001B[38;5;241;43m10000.0\u001B[39;49m\u001B[43m}\u001B[49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[43m{\u001B[49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[38;5;124;43mdate\u001B[39;49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[43m:\u001B[49m\u001B[43m \u001B[49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[38;5;124;43m2023-06-30\u001B[39;49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[38;5;124;43mamount\u001B[39;49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[43m:\u001B[49m\u001B[43m \u001B[49m\u001B[38;5;241;43m10000.0\u001B[39;49m\u001B[43m}\u001B[49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[43m{\u001B[49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[38;5;124;43mdate\u001B[39;49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[43m:\u001B[49m\u001B[43m \u001B[49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[38;5;124;43m2024-06-30\u001B[39;49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[38;5;124;43mamount\u001B[39;49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[43m:\u001B[49m\u001B[43m \u001B[49m\u001B[38;5;241;43m10000.0\u001B[39;49m\u001B[43m}\u001B[49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[43m{\u001B[49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[38;5;124;43mdate\u001B[39;49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[43m:\u001B[49m\u001B[43m \u001B[49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[38;5;124;43m2025-06-30\u001B[39;49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[38;5;124;43mamount\u001B[39;49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[43m:\u001B[49m\u001B[43m \u001B[49m\u001B[38;5;241;43m10000.0\u001B[39;49m\u001B[43m}\u001B[49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[43m{\u001B[49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[38;5;124;43mdate\u001B[39;49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[43m:\u001B[49m\u001B[43m \u001B[49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[38;5;124;43m2026-06-30\u001B[39;49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[38;5;124;43mamount\u001B[39;49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[43m:\u001B[49m\u001B[43m \u001B[49m\u001B[38;5;241;43m10000.0\u001B[39;49m\u001B[43m}\u001B[49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[43m{\u001B[49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[38;5;124;43mdate\u001B[39;49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[43m:\u001B[49m\u001B[43m \u001B[49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[38;5;124;43m2027-06-30\u001B[39;49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[38;5;124;43mamount\u001B[39;49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[43m:\u001B[49m\u001B[43m \u001B[49m\u001B[38;5;241;43m10000.0\u001B[39;49m\u001B[43m}\u001B[49m\u001B[43m]\u001B[49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[38;5;124;43mlodgement_date\u001B[39;49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[43m:\u001B[49m\u001B[43m \u001B[49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[38;5;124;43m2021-06-30\u001B[39;49m\u001B[38;5;124;43m\"\u001B[39;49m\u001B[43m}\u001B[49m\u001B[43m)\u001B[49m\n",
      "File \u001B[0;32m~/repos/koo5/accounts-assessor/0/accounts-assessor/sources/services/app/div7a.py:324\u001B[0m, in \u001B[0;36mdiv7a2_from_json\u001B[0;34m(j, tmp_dir_path)\u001B[0m\n\u001B[1;32m    321\u001B[0m \tjson\u001B[38;5;241m.\u001B[39mdump(j, ooo, indent\u001B[38;5;241m=\u001B[39m\u001B[38;5;28;01mTrue\u001B[39;00m)\n\u001B[1;32m    322\u001B[0m \t\u001B[38;5;28mprint\u001B[39m(\u001B[38;5;124mf\u001B[39m\u001B[38;5;124m'\u001B[39m\u001B[38;5;124m</code></pre></big>\u001B[39m\u001B[38;5;124m'\u001B[39m, file\u001B[38;5;241m=\u001B[39mooo)\n\u001B[0;32m--> 324\u001B[0m r \u001B[38;5;241m=\u001B[39m \u001B[43mdiv7a2_from_json2\u001B[49m\u001B[43m(\u001B[49m\u001B[43mooo\u001B[49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[43mj\u001B[49m\u001B[43m)\u001B[49m\n\u001B[1;32m    326\u001B[0m \u001B[38;5;28;01mif\u001B[39;00m ooo:\n\u001B[1;32m    327\u001B[0m \t\u001B[38;5;28mprint\u001B[39m(\u001B[38;5;124mf\u001B[39m\u001B[38;5;124m'\u001B[39m\u001B[38;5;124m<h3>response</h3>\u001B[39m\u001B[38;5;124m'\u001B[39m, file\u001B[38;5;241m=\u001B[39mooo)\n",
      "File \u001B[0;32m~/repos/koo5/accounts-assessor/0/accounts-assessor/sources/services/app/div7a.py:369\u001B[0m, in \u001B[0;36mdiv7a2_from_json2\u001B[0;34m(ooo, j)\u001B[0m\n\u001B[1;32m    365\u001B[0m \tlog\u001B[38;5;241m.\u001B[39mwarn(records)\n\u001B[1;32m    367\u001B[0m \u001B[38;5;66;03m# computation\u001B[39;00m\n\u001B[0;32m--> 369\u001B[0m records \u001B[38;5;241m=\u001B[39m \u001B[43mdiv7a\u001B[49m\u001B[43m(\u001B[49m\u001B[43mooo\u001B[49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[43mrecords\u001B[49m\u001B[43m)\u001B[49m\n\u001B[1;32m    371\u001B[0m \u001B[38;5;66;03m# answer\u001B[39;00m\n\u001B[1;32m    373\u001B[0m overview \u001B[38;5;241m=\u001B[39m []\n",
      "File \u001B[0;32m~/repos/koo5/accounts-assessor/0/accounts-assessor/sources/services/app/div7a.py:151\u001B[0m, in \u001B[0;36mdiv7a\u001B[0;34m(ooo, records)\u001B[0m\n\u001B[1;32m    147\u001B[0m \u001B[38;5;28;01mdef\u001B[39;00m \u001B[38;5;21mdiv7a\u001B[39m(ooo, records):\n\u001B[1;32m    148\u001B[0m \n\u001B[1;32m    149\u001B[0m \t\u001B[38;5;66;03m# we begin with loan_start, optional opening_balance, possible lodgement day, and then repayments.\u001B[39;00m\n\u001B[1;32m    150\u001B[0m \ttables \u001B[38;5;241m=\u001B[39m [\u001B[38;5;28mlist\u001B[39m(records)]\n\u001B[0;32m--> 151\u001B[0m \t\u001B[43mstep\u001B[49m\u001B[43m(\u001B[49m\u001B[43mooo\u001B[49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[43mtables\u001B[49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[38;5;28;43minput\u001B[39;49m\u001B[43m)\u001B[49m\n\u001B[1;32m    152\u001B[0m \t\u001B[38;5;66;03m# insert opening_balance record if it's not there\u001B[39;00m\n\u001B[1;32m    153\u001B[0m \tstep(ooo, tables, ensure_opening_balance_exists)\n",
      "File \u001B[0;32m~/repos/koo5/accounts-assessor/0/accounts-assessor/sources/services/app/div7a.py:175\u001B[0m, in \u001B[0;36mstep\u001B[0;34m(ooo, tables, f, final)\u001B[0m\n\u001B[1;32m    173\u001B[0m \u001B[38;5;28;01mdef\u001B[39;00m \u001B[38;5;21mstep\u001B[39m(ooo, tables, f, final\u001B[38;5;241m=\u001B[39m\u001B[38;5;28;01mFalse\u001B[39;00m):\n\u001B[1;32m    174\u001B[0m \tt1 \u001B[38;5;241m=\u001B[39m tables[\u001B[38;5;241m-\u001B[39m\u001B[38;5;241m1\u001B[39m]\n\u001B[0;32m--> 175\u001B[0m \t\u001B[43mcheck_invariants\u001B[49m\u001B[43m(\u001B[49m\u001B[43mt1\u001B[49m\u001B[43m)\u001B[49m\n\u001B[1;32m    176\u001B[0m \tt2 \u001B[38;5;241m=\u001B[39m [r\u001B[38;5;241m.\u001B[39mcopy() \u001B[38;5;28;01mfor\u001B[39;00m r \u001B[38;5;129;01min\u001B[39;00m t1] \n\u001B[1;32m    177\u001B[0m \tf(t2)\n",
      "File \u001B[0;32m~/repos/koo5/accounts-assessor/0/accounts-assessor/sources/services/app/div7a_checks.py:42\u001B[0m, in \u001B[0;36mcheck_invariants\u001B[0;34m(records)\u001B[0m\n\u001B[1;32m     38\u001B[0m \t\t\u001B[38;5;28;01mraise\u001B[39;00m MyException(\u001B[38;5;124m'\u001B[39m\u001B[38;5;124mOpening balance is not positive\u001B[39m\u001B[38;5;124m'\u001B[39m)\n\u001B[1;32m     40\u001B[0m \u001B[38;5;66;03m# \tloan_start is before calculation_start:\u001B[39;00m\n\u001B[0;32m---> 42\u001B[0m \u001B[38;5;28;01mif\u001B[39;00m records\u001B[38;5;241m.\u001B[39mindex(\u001B[43mone\u001B[49m\u001B[43m(\u001B[49m\u001B[43m[\u001B[49m\u001B[43mr\u001B[49m\u001B[43m \u001B[49m\u001B[38;5;28;43;01mfor\u001B[39;49;00m\u001B[43m \u001B[49m\u001B[43mr\u001B[49m\u001B[43m \u001B[49m\u001B[38;5;129;43;01min\u001B[39;49;00m\u001B[43m \u001B[49m\u001B[43mrecords\u001B[49m\u001B[43m \u001B[49m\u001B[38;5;28;43;01mif\u001B[39;49;00m\u001B[43m \u001B[49m\u001B[43mr\u001B[49m\u001B[38;5;241;43m.\u001B[39;49m\u001B[38;5;18;43m__class__\u001B[39;49m\u001B[43m \u001B[49m\u001B[38;5;241;43m==\u001B[39;49m\u001B[43m \u001B[49m\u001B[43mcalculation_start\u001B[49m\u001B[43m]\u001B[49m\u001B[43m)\u001B[49m) \u001B[38;5;241m<\u001B[39m\u001B[38;5;241m=\u001B[39m records\u001B[38;5;241m.\u001B[39mindex(one([r \u001B[38;5;28;01mfor\u001B[39;00m r \u001B[38;5;129;01min\u001B[39;00m records \u001B[38;5;28;01mif\u001B[39;00m r\u001B[38;5;241m.\u001B[39m\u001B[38;5;18m__class__\u001B[39m \u001B[38;5;241m==\u001B[39m loan_start])):\n\u001B[1;32m     43\u001B[0m \t\u001B[38;5;28;01mraise\u001B[39;00m MyException(\u001B[38;5;124m'\u001B[39m\u001B[38;5;124mloan_start is before calculation_start\u001B[39m\u001B[38;5;124m'\u001B[39m)\n\u001B[1;32m     45\u001B[0m \u001B[38;5;28;01mif\u001B[39;00m records\u001B[38;5;241m.\u001B[39mindex(one([r \u001B[38;5;28;01mfor\u001B[39;00m r \u001B[38;5;129;01min\u001B[39;00m records \u001B[38;5;28;01mif\u001B[39;00m r\u001B[38;5;241m.\u001B[39m\u001B[38;5;18m__class__\u001B[39m \u001B[38;5;241m==\u001B[39m calculation_start])) \u001B[38;5;241m>\u001B[39m\u001B[38;5;241m=\u001B[39m records\u001B[38;5;241m.\u001B[39mindex(one([r \u001B[38;5;28;01mfor\u001B[39;00m r \u001B[38;5;129;01min\u001B[39;00m records \u001B[38;5;28;01mif\u001B[39;00m r\u001B[38;5;241m.\u001B[39m\u001B[38;5;18m__class__\u001B[39m \u001B[38;5;241m==\u001B[39m loan_term_end])):\n",
      "File \u001B[0;32m~/repos/koo5/accounts-assessor/0/accounts-assessor/sources/services/app/div7a_impl.py:272\u001B[0m, in \u001B[0;36mone\u001B[0;34m(xs)\u001B[0m\n\u001B[1;32m    270\u001B[0m \u001B[38;5;28;01mdef\u001B[39;00m \u001B[38;5;21mone\u001B[39m(xs):\n\u001B[1;32m    271\u001B[0m \t\u001B[38;5;28;01mif\u001B[39;00m \u001B[38;5;28mlen\u001B[39m(xs) \u001B[38;5;241m!=\u001B[39m \u001B[38;5;241m1\u001B[39m:\n\u001B[0;32m--> 272\u001B[0m \t\t\u001B[38;5;28;01mraise\u001B[39;00m MyException(\u001B[38;5;124mf\u001B[39m\u001B[38;5;124m'\u001B[39m\u001B[38;5;124mExpected one element, but got \u001B[39m\u001B[38;5;132;01m{\u001B[39;00m\u001B[38;5;28mlen\u001B[39m(xs)\u001B[38;5;132;01m}\u001B[39;00m\u001B[38;5;124m'\u001B[39m)\n\u001B[1;32m    273\u001B[0m \t\u001B[38;5;28;01mreturn\u001B[39;00m xs[\u001B[38;5;241m0\u001B[39m]\n",
      "\u001B[0;31mMyException\u001B[0m: Expected one element, but got 0"
     ]
    }
   ],
   "source": [
    "%load_ext autoreload\n",
    "%autoreload 2\n",
    "from app.div7a import *\n",
    "#div7a2_from_json({\"loan_year\": 2020, \"full_term\": 7, \"opening_balance\": 100000.0, \"opening_balance_year\": 2020, \"repayments\": [{\"date\": \"2023-11-25\", \"amount\": 0.0}], \"lodgement_date\": \"2021-06-30\"})\n",
    "div7a2_from_json({\"loan_year\": 2020, \"full_term\": 7, \"opening_balance\": 100000.0, \"opening_balance_year\": 2020, \"repayments\": [{\"date\": \"2021-06-30\", \"amount\": 10000.0}, {\"date\": \"2022-06-30\", \"amount\": 10000.0}, {\"date\": \"2023-06-30\", \"amount\": 10000.0}, {\"date\": \"2024-06-30\", \"amount\": 10000.0}, {\"date\": \"2025-06-30\", \"amount\": 10000.0}, {\"date\": \"2026-06-30\", \"amount\": 10000.0}, {\"date\": \"2027-06-30\", \"amount\": 10000.0}], \"lodgement_date\": \"2021-06-30\"})"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
